ROOT/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import (PasswordResetView, 
                                       PasswordResetDoneView, 
                                       PasswordResetConfirmView, 
                                       PasswordResetCompleteView)

from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path("i18n/", include("django.conf.urls.i18n")),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('password-reset/', PasswordResetView.as_view(template_name='app_users/password-reset.html'), name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(template_name='app_users/password-reset-done.html'), name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='app_users/password-reset-confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(template_name='app_users/password-reset-complete.html'), name='password_reset_complete'),
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),

    path('', include('app_main.urls')),
    path('users/', include('app_users.urls')),
)


if settings.DEBUG:
    urlpatterns += static(prefix=settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(prefix=settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app_main/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.DevelopersView.as_view(), name='developers'),

    path('projects/', views.ProjectsView.as_view(), name='projects'),
    path('project-create/', views.ProjectCreate.as_view(), name='project_create'),
    path('project/<int:project_id>', views.ProjectDetail.as_view(), name='project_detail'),
    
    path('profile/<int:user_id>', views.ProfileView.as_view(), name='profile_detail'),
    path('send-message/<int:receiver_id>', views.handle_message_submission, name='send_message'),
    path('inbox/', views.InboxView.as_view(), name='inbox'),
    path('message/<int:message_id>/', views.MessageView.as_view(), name='message'),
]

app_main/models.py
from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()


class Project(models.Model):
    owner = models.ForeignKey(to=User, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    description = models.TextField()
    image = models.ImageField(upload_to='project-photos/',
                              default='project-photos/project-default.png', null=True, blank=True)
    tags = models.ManyToManyField(to='Tag', blank=True)
    source_link = models.URLField(null=True, blank=True)
    demo_link = models.URLField(null=True, blank=True)

    def __str__(self):
        return f'{self.name} - {self.owner.fullname}'


class Tag(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class Message(models.Model):
    sender = models.ForeignKey(to=User, related_name='sent_messages', on_delete=models.SET_NULL, null=True)
    receiver = models.ForeignKey(to=User, related_name='recieved_messages', on_delete=models.CASCADE)
    fullname = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    subject = models.CharField(max_length=100)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.sender} - {self.receiver} - {self.body[:50]}'

app_users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _

from .managers import MyUserManager as UserManager


class User(AbstractUser):
    first_name = models.CharField(_('First name'), max_length=100)
    last_name = models.CharField('Last name', max_length=100)
    username = models.CharField('Username', max_length=100, null=True, blank=True)
    email = models.EmailField('Email', max_length=100, unique=True)
    bio = models.TextField('About', null=True, blank=True)
    profile_image = models.ImageField('Profile image',
                                      default='profile-images/user-default.png',
                                      upload_to='profile-images/',
                                      null=True, blank=True)
    location = models.CharField('Location', max_length=100, null=True, blank=True)
    occupation = models.CharField('Occupation', max_length=200, null=True, blank=True)
    social_telegram = models.URLField('Telegram', max_length=200, null=True, blank=True)
    social_instagram = models.URLField('Instagram', max_length=200, null=True, blank=True)
    social_facebook = models.URLField('Facebook', max_length=200, null=True, blank=True)
    social_twitter = models.URLField('Twitter', max_length=200, null=True, blank=True)
    social_whatsapp = models.URLField('Whatsapp', max_length=200, null=True, blank=True)
    social_linkedin = models.URLField('LinkedIn', max_length=200, null=True, blank=True)
    social_youtube = models.URLField('YouTube', max_length=200, null=True, blank=True)
    social_github = models.URLField('GitHub', max_length=200, null=True, blank=True)
    social_website = models.URLField('Website', max_length=200, null=True, blank=True)

    objects = UserManager()
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    @property
    def fullname(self):
        return f"{self.first_name} {self.last_name}"

    def get_fullname(self):
        return f"{self.first_name} {self.last_name}"

    def set_fullname(self, value):
        names = value.split()
        self.first_name, self.last_name = names[0], " ".join(names[1:])

    fullname = property(get_fullname, set_fullname)


class Skill(models.Model):
    owner = models.ForeignKey(to=User, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return f'{self.owner} - {self.name}'

app_main/forms.py
from django.forms import ModelForm

from . import models
from app_users.forms import AddInputClass


class ProjectForm(AddInputClass, ModelForm):
    class Meta:
        model = models.Project
        fields = ['name', 'description', 'image', 'source_link', 'demo_link']


class MessageForm(AddInputClass, ModelForm):
    class Meta:
        model = models.Message
        fields = ['fullname', 'email', 'subject', 'body']

app_main/views.py
from typing import Any
from django.db.models import Q
from django.db.models.query import QuerySet
from django.shortcuts import redirect, render, get_object_or_404
from django.views.generic import ListView, CreateView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import get_user_model
from django.urls import reverse, reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.core.paginator import Paginator

from .models import Project, Tag, Message
from .forms import ProjectForm, MessageForm


User = get_user_model()


class CustomRangeForPagination:
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        
        page_obj = context['page_obj']
        left_index = page_obj.number - 1
        right_index = page_obj.number + 1

        if left_index < 1:
            left_index = 1
        
        if right_index > page_obj.paginator.num_pages:
            right_index = page_obj.paginator.num_pages

        custom_range = range(left_index, right_index + 1)
        context['custom_range'] = custom_range
        return context


class DevelopersView(CustomRangeForPagination, ListView):
    template_name = 'app_main/developers.html'
    paginator_class = Paginator
    paginate_by = 3

    def get_queryset(self):
        return User.objects.all()
    
    context_object_name = 'developers'


class ProjectsView(CustomRangeForPagination, ListView):
    model = Project
    template_name = 'app_main/projects.html'
    context_object_name = 'projects'
    paginator_class = Paginator
    paginate_by = 3


class ProjectCreate(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy("login")
    model = Project
    template_name = 'app_main/project_form.html'
    form_class = ProjectForm
    extra_context = {
        'btn_text': 'Create project'
    }

    def get_success_url(self):
        return reverse('account', kwargs={'user_id': self.request.user.id})

    def dispatch(self, request, *args, **kwargs):
        if request.method == 'POST':
            tags = self.request.POST.get('tags', '').split(',')
            project_form = ProjectForm(self.request.POST)

            if project_form.is_valid():
                project = project_form.save(commit=False)
                project.owner = self.request.user
                project.save()

                # Process and add tags
                for tag_name in tags:
                    tag, created = Tag.objects.get_or_create(
                        name=tag_name.strip())
                    project.tags.add(tag.lower())

                project.save()  # Final save with tags
                return redirect("account", user_id=self.request.user.id)

            # If form is invalid, render the form with errors
            return redirect("project_create", kwargs={'user_id': self.request.user.id})

        return super().dispatch(request, *args, **kwargs)


class ProjectDetail(DetailView):
    model = Project
    pk_url_kwarg = 'project_id'
    template_name = 'app_main/project.html'


class ProfileView(DetailView):
    model = User
    pk_url_kwarg = 'user_id'
    template_name = 'app_main/profile.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['dev_skills'] = self.get_object(
        ).skill_set.exclude(description="")
        context['other_skills'] = self.get_object(
        ).skill_set.filter(description="")
        return context


def handle_message_submission(request, receiver_id):
    form = MessageForm(request.POST or None)

    if request.user.is_authenticated:
        form.fields.pop('fullname', None)
        form.fields.pop('email', None)

    if request.method == 'POST':

        if form.is_valid():
            message = form.save(commit=False)

            if request.user.is_authenticated:
                message.sender = request.user
                message.fullname = request.user.fullname
                message.email = request.user.email

            # Retrieve the receiver user with error handling
            message.receiver = get_object_or_404(User, id=receiver_id)
            message.save()
            return redirect('profile_detail', user_id=receiver_id)

    print(form.fields)
    context = {
        'form': form,
        'btn_text': _('Send message')
    }
    return render(request, 'form.html', context)


class InboxView(ListView):
    queryset = Message.objects.all().order_by('is_read', '-created')
    template_name = 'app_main/inbox.html'
    context_object_name = 'messages'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['unread_messages_count'] = Message.objects.filter(is_read=False).count()
        return context


class MessageView(DetailView):
    model = Message
    template_name = 'app_main/message.html'
    context_object_name = 'message'
    pk_url_kwarg = 'message_id'

    def dispatch(self, request, *args, **kwargs):
        message = self.get_object()
        message.is_read = True
        message.save()
        return super().dispatch(request, *args, **kwargs)

app_main/templates/app_main/developers.html
{% extends 'base.html' %} 
{% load i18n %}

{% block content %}
<main class="home">
	<section class="hero-section text-center">
		<div class="container container--narrow">
			<div class="hero-section__box">
				{% blocktrans %}
					<h2>CONNECT WITH <span>DEVELOPERS</span></h2>
					<h2>FROM AROUND THE WORLD</h2>
				{% endblocktrans %}
			</div>

			<div class="hero-section__search">
				<form class="form" action="" method="get">
					<div class="form__field">
						<label for="formInput#search">{% trans 'Search Developers' %}</label>
						<input
							class="input input--text"
							id="formInput#search"
							type="text"
							name="query"
							placeholder="{% trans 'Search by developer name' %}"
							value=""
						/>
					</div>

					<input class="btn btn--sub btn--lg" type="submit" value="{% trans 'Search' %}" />
				</form>
			</div>
		</div>
	</section>
	<!-- Search Result: DevList -->
	<section class="devlist">
		<div class="container">
			<div class="grid grid--three">
				{% for developer in developers %}
					<div class="column card">
						<div class="dev">
							<a
								href="{% url 'profile_detail' developer.id %}"
								class="card__body"
							>
								<div class="dev__profile">
									<img
										class="avatar avatar--md"
										src="{{ developer.profile_image.url }}"
										alt="{{ developer.fullname }}"
									/>
									<div class="dev__meta">
										<h3>{{ developer.fullname }}</h3>
										<h5>{{ developer.occupation }}</h5>
									</div>
								</div>
								<p class="dev__info">
									{{ developer.bio|truncatechars:200 }}
								</p>
								<div class="dev__skills">
									{% for skill in developer.skill_set.all|slice:6 %}
										<span class="tag tag--pill tag--main">
											<small>{{ skill.name }}</small>
										</span>
									{% endfor %}
								</div>
							</a>
						</div>
					</div>
				{% endfor %}
			</div>
		</div>
	</section>

	{% include 'components/_pagination.html' with custom_range=custom_range page_obj=page_obj %}

</main>

{% endblock content %}

app_main/templates/app_main/inbox.html
{% extends 'base.html' %}

{% block content %}

<main class="inbox my-xl">
    <div class="content-box">
      <h3 class="inbox__title">New Messages(<span>{{ unread_messages_count }}</span>)</h3>
      <ul class="messages">
        {% for message in messages %}
            <li class="message {% if not message.is_read %} message--unread {% endif %} ">
            <a href="{% url 'message' message.id %}">
                <span class="message__author">{{ message.fullname }}</span>
                <span class="message__subject">{{ message.subject }}</span>
                <span class="message__date">{{ message.created|date:"M d, Y, H:m:i" }}</span>
            </a>
            </li>
        {% endfor %}
      </ul>
    </div>
  </main>

{% endblock content %}

app_main/templates/app_main/message.html
{% extends 'base.html' %}

{% block content %}

<main class="messagePage my-xl">
    <div class="content-box">
      <div class="message">
        <a class="backButton" href="{{ request.META.HTTP_REFERER }}"><i class="bi bi-arrow-left"></i></a>
        <h2 class="message__subject">{{ message.subject }}</h4>
          <a href="{% if message.sender %} {% url 'profile_detail' message.sender.id %} {% else %}mailto:{{ message.email }}{% endif %}" class="message__author">{{ message.fullname }}</a>
          <p class="message__date">May 31, 2021, 04:37 PM</p>
          <div class="message__body">
            ........
            <br /><br />
            ...........
          </div>
      </div>
    </div>
</main>

{% endblock content %}

app_main/templates/app_main/profile.html
{% extends 'base.html' %}

{% block content %}
<main class="profile my-md">
    <div class="container">
        <div class="layout">
            <div class="column column--1of3">
                <div class="card text-center">
                  <div class="card__body dev">
                    <img class="avatar avatar--xl" src="{{ object.profile_image.url }}" alt="{{ object.fullname }}" />
                    <h2 class="dev__name">{{ object.fullname }}</h2>
                    <p class="dev__title">{{ object.occupation }}</p>
                    <p class="dev__location">Based in {{ object.location }}</p>
                    <ul class="dev__social">
                      {% if object.social_telegram %}
                      <li>
                        <a title="Telegram" href="{{ object.social_telegram }}" target="_blank">
                          <i class="bi bi-telegram"></i>
                        </a>
                      </li>
                      {% endif %}
                      
                      {% if object.social_instagram %}
                      <li>
                        <a title="Instagram" href="{{ object.social_instagram }}" target="_blank">
                          <i class="bi bi-instagram"></i>
                        </a>
                      </li>
                      {% endif %}
                      
                      {% if object.social_facebook %}
                      <li>
                        <a title="Facebook" href="{{ object.social_facebook }}" target="_blank">
                          <i class="bi bi-facebook"></i>
                        </a>
                      </li>
                      {% endif %}
                      
                      {% if object.social_twitter %}
                      <li>
                        <a title="Twitter" href="{{ object.social_twitter }}" target="_blank">
                          <i class="bi bi-twitter"></i>
                        </a>
                      </li>
                      {% endif %}
                      
                      {% if object.social_whatsapp %}
                      <li>
                        <a title="WhatsApp" href="{{ object.social_whatsapp }}" target="_blank">
                          <i class="bi bi-whatsapp"></i>
                        </a>
                      </li>
                      {% endif %}
                      
                      {% if object.social_linkedin %}
                      <li>
                        <a title="LinkedIn" href="{{ object.social_linkedin }}" target="_blank">
                          <i class="bi bi-linkedin"></i>
                        </a>
                      </li>
                      {% endif %}
                      
                      {% if object.social_youtube %}
                      <li>
                        <a title="YouTube" href="{{ object.social_youtube }}" target="_blank">
                          <i class="bi bi-youtube"></i>
                        </a>
                      </li>
                      {% endif %}
                      
                      {% if object.social_github %}
                      <li>
                        <a title="GitHub" href="{{ object.social_github }}" target="_blank">
                          <i class="bi bi-github"></i>
                        </a>
                      </li>
                      {% endif %}
                      
                      {% if object.social_website %}
                      <li>
                        <a title="Personal Website" href="{{ object.social_website }}" target="_blank">
                          <i class="bi bi-globe"></i>
                        </a>
                      </li>
                      {% endif %}							
                    </ul>
                    {% if request.user.id != object.id %}
                      <a href="{% url 'send_message' object.id %}" class="btn btn--sub btn--lg">Send Message </a>
                    {% endif %}
                  </div>
                </div>
            </div>
            <div class="column column--2of3">
                <div class="devInfo">
                    <h3 class="devInfo__title">About Me</h3>
                    <p class="devInfo__about">
                      {{ objects.bio|linebreaksbr }}
                    </p>
                </div>
                <div class="devInfo">
                    <h3 class="devInfo__title">Skills</h3>
                    <div class="devInfo__skills">
                        {% for skill in dev_skills %}
                            <div class="devSkill">
                                <h4 class="devSkill__title">{{ skill.name }}</h4>
                                <p class="devSkill__info">
                                  {{ skill.description|linebreaksbr }}
                                </p>
                            </div>
                        {% endfor %}
                        <h3 class="devInfo__subtitle">Other Skills</h3>
                        <div class="devInfo__otherSkills">
                            {% for skill in other_skills %}
                            <span class="tag tag--pill tag--sub tag--lg">
                              <small>{{ skill.name }}</small>
                            </span>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <div class="devInfo">
                  <h3 class="devInfo__title">Projects</h3>
                  <div class="grid grid--two">
                    {% for project in object.project_set.all %}
                    <div class="column">
                      <div class="card project">
                        <a href="{% url 'project_detail' project.id %}" class="project">
                          <img class="project__thumbnail" src="{{ project.image.url }}" alt="{{ project.name }}" />
                          <div class="card__body">
                            <h3 class="project__title">{{ project.name }}</h3>
                            <p><a class="project__author" href="{% url 'profile_detail' object.id %}">By {{ project.owner.fullname}}</a></p>
              
                            <div class="project__tags">
                              {% for tag in project.tags.all %}
                                <span class="tag tag--pill tag--main">
                                  <small>{{ tag.name }}</small>
                                </span>
                              {% endfor %}

                            </div>
                          </div>
                        </a>
                      </div>
                    </div>
                    {% endfor %}
                  </div>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock content %}

app_main/templates/app_main/project.html
{% extends 'base.html' %}

{% block content %}
<main class="singleProject my-md">
    <div class="container">
        <div class="layout">
        <div class="column column--1of3">
            <h3 class="singleProject__subtitle">Tools & Stacks</h3>
            <div class="singleProject__toolStack">
            {% for tag in project.tags.all %}
                <span class="tag tag--pill tag--sub tag--lg">
                    <small>{{ tag.name|upper }}</small>
                </span>
            {% endfor %}
            </div>
            {% if object.source_link %}
                <a class="singleProject__liveLink" href="{{ object.source_link }}" target="_blank">
                    <i class="bi bi-link-45deg"></i>
                    Source Code
                </a>
            {% endif %}
            {% if object.demo_link %}
                <a class="singleProject__liveLink" href="{{ object.demo_link }}" target="_blank">
                    <i class="bi bi-globe"></i>
                    Demo Code
                </a>
            {% endif %}
        </div>
        <div class="column column--2of3">
            <img class="singleProject__preview" src="{{ object.image.url }}" alt="{{ object.name }}" />
            <a href="{% url 'profile_detail' object.owner.id %}" class="singleProject__developer">{{ object.owner.fullname }}</a>
            <h2 class="singleProject__title">{{ object.name }}</h2>
            <h3 class="singleProject__subtitle">About the Project</h3>
            <div class="singleProject__info">
                {{ object.description|linebreaksbr }}
            </div>

            <div class="comments">
            <h3 class="singleProject__subtitle">Feedback</h3>

            <form class="form" action="#" method="POST">
                <!-- Textarea -->
                <div class="form__field">
                <label for="formInput#textarea">Comments: </label>
                <textarea class="input input--textarea" name="message" id="formInput#textarea"
                    placeholder="Write your comments here..."></textarea>
                </div>
                <input class="btn btn--sub btn--lg" type="submit" value="Comments" />
            </form>
            <div class="commentList">
                <div class="comment">
                <a href="profile.html">
                    <img class="avatar avatar--md"
                    src="https://pbs.twimg.com/profile_images/1335382240931368961/b3wSZKj4_400x400.jpg" alt="user" />
                </a>
                <div class="comment__details">
                    <a href="profile.html" class="comment__author">Sulamita Ivanov</a>
                    <p class="comment__info">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit alias numquam perferendis
                    mollitia minus minima exercitationem possimus ab deserunt qui, soluta iusto doloribus eveniet
                    similique consequuntur ratione, dignissimos ut magni laborum quo.
                    </p>
                </div>
                </div>
                <div class="comment">
                <a href="profile.html">
                    <img class="avatar avatar--md" src="https://avatars.githubusercontent.com/u/33843378" alt="user" />
                </a>
                <div class="comment__details">
                    <a href="profile.html" class="comment__author">Dennis Ivanov</a>
                    <p class="comment__info">
                    Consectetur adipisicing elit. Reprehenderit alias numquam perferendis mollitia minus minima
                    exercitationem possimus ab deserunt qui, ratione, dignissimos ut magni laborum quo.
                    </p>
                </div>
                </div>
            </div>
            </div>
        </div>
        </div>
    </div>
    </div>

</main>

{% endblock content %}

app_main/templates/app_main/project_form.html
{% extends 'base.html' %} 
{% load static %}

{% block content %}
<main class="formPage my-xl">
	<div class="content-box">
		<div class="formWrapper">
			<a class="backButton" href="{{ request.META.HTTP_REFERER }}">
				<i class="bi bi-arrow-left"></i>
			</a>
			<br />

			<form class="form" method="POST" action="" enctype="multipart/form-data">
				{% csrf_token %}

				{% for field in form %}
                    {% if field.name == 'description' %}
                        <div class="form__field">
                            <label for="id_{{ field.name }}">{{ field.label }}: </label>
                            {{ field }}
                        </div>
                        <div class="form__field">
                            <div id="tags" style="margin-bottom: 10px;"></div>
                            <input type="hidden" name="tags" id="tags_hidden">
                            <input class="input" type="text" name="custom_tags" id="id_tags">
                        </div>
                    {% else %}
                        <div class="form__field">
                            <label for="id_{{ field.name }}">{{ field.label }}: </label>
                            {{ field }}
                        </div>
                    {% endif %}
				{% endfor %}

				<button class="btn btn--sub btn--lg my-md" type="submit" id="submit-form-btn">{{ btn_text }}</button>
			</form>
		</div>
	</div>
</main>

<script type="text/javascript">
    const tagsInput = document.getElementById('id_tags');
    const tagsHiddenInput = document.getElementById('tags_hidden');
    const tagsContainer = document.getElementById('tags');

    // Helper function to update the hidden input with all current tags
    const updateHiddenInput = () => {
        const tags = Array.from(document.querySelectorAll('.tag-text')).map(tag => tag.textContent.trim());
        tagsHiddenInput.value = tags.join(',');
    };

    // Event handler for adding new tags
    const addTag = (newTag) => {
        const tagElement = `
            <span class="tag tag--pill tag--sub tag--lg">
                <small class="tag-text" style="display: flex; align-items: center; gap: 10px;">
                    ${newTag}
                    <i class="bi bi-x-lg tag-close" style="cursor: pointer;"></i>
                </small>
            </span>
        `;
        tagsContainer.innerHTML += tagElement;
        updateHiddenInput();
    };

    // Main input listener for handling new tag creation
    tagsInput.addEventListener('keyup', (event) => {
        if (event.key === ',' || event.key === ' ') {
            const newTag = event.target.value.replace(',', '').trim();

            if (newTag && ![...document.querySelectorAll('.tag-text')].some(tag => tag.textContent.trim() === newTag)) {
                addTag(newTag);
            }
            tagsInput.value = '';  // Clear input after adding the tag
        }
    });

    // Event delegation for removing tags
    tagsContainer.addEventListener('click', (event) => {
        if (event.target.classList.contains('tag-close')) {
            event.target.closest('.tag').remove();
            updateHiddenInput();
        }
    });
</script>
{% endblock content %}

app_main/templates/app_main/send_message.html
{% extends 'base.html' %}

{% block content %}
<main class="messagePage my-xl">
    <div class="content-box">
      <div class="message">
        <a class="backButton" href="inbox.html"><i class="im im-angle-left"></i></a>
        <h2 class="message__subject">Working Opportunity for Web Design Company</h4>
          <a href="profile.html" class="message__author">Dennis Ivanov</a>
          <p class="message__date">May 31, 2021, 04:37 PM</p>
          <div class="message__body">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, ea? Facere minus vel nam, quas nisi dolore
            possimus tempora commodi. Praesentium nisi totam quas pariatur culpa nostrum dolore, nemo voluptatem!
            <br /><br />
            Voluptate dolores veniam ducimus cumque, harum fuga quaerat, culpa distinctio voluptas magnam a unde
            reiciendis similique necessitatibus obcaecati voluptatibus deserunt voluptatum numquam ullam in ipsum, ea
            aperiam. Dolorum rerum pariatur quaerat. Debitis tempora aliquid libero alias aperiam illo fuga ipsum magni
            quia.
          </div>
      </div>
    </div>
  </main>
{% endblock content %}