ROOT/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import (PasswordResetView, 
                                       PasswordResetDoneView, 
                                       PasswordResetConfirmView, 
                                       PasswordResetCompleteView)

from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path("i18n/", include("django.conf.urls.i18n")),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('password-reset/', PasswordResetView.as_view(template_name='app_users/password-reset.html'), name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(template_name='app_users/password-reset-done.html'), name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='app_users/password-reset-confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(template_name='app_users/password-reset-complete.html'), name='password_reset_complete'),
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),

    path('', include('app_main.urls')),
    path('users/', include('app_users.urls')),
)


if settings.DEBUG:
    urlpatterns += static(prefix=settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(prefix=settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app_users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView


from . import views


urlpatterns = [
    path('account/<int:user_id>/', views.AccountView.as_view(), name='account'),
    path('update-account/<int:user_id>/', views.UpdateAccount.as_view(), name='update_account'),


    path('registration/', views.UserRegistrationView.as_view(), name='registration'),
    path('login/', LoginView.as_view(template_name='app_users/login.html'), name='login'),
    path('logout/', views.logout_view, name='logout'),

    path('create-skill/', views.CreateSkillView.as_view(), name='create_skill'),
    path('update-skill/<int:skill_id>/', views.UpdateSkillView.as_view(), name='update_skill'),
    path('delete-skill/<int:skill_id>/', views.DeleteSkillView.as_view(), name='delete_skill'),


]

app_main/models.py
from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()


class Project(models.Model):
    owner = models.ForeignKey(to=User, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    description = models.TextField()
    image = models.ImageField(upload_to='project-photos/',
                              default='project-photos/project-default.png', null=True, blank=True)
    tags = models.ManyToManyField(to='Tag', blank=True)
    source_link = models.URLField(null=True, blank=True)
    demo_link = models.URLField(null=True, blank=True)

    def __str__(self):
        return f'{self.name} - {self.owner.fullname}'


class Tag(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class Message(models.Model):
    sender = models.ForeignKey(to=User, related_name='sent_messages', on_delete=models.SET_NULL, null=True)
    receiver = models.ForeignKey(to=User, related_name='recieved_messages', on_delete=models.CASCADE)
    fullname = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    subject = models.CharField(max_length=100)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.sender} - {self.receiver} - {self.body[:50]}'

app_users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _

from .managers import MyUserManager as UserManager


class User(AbstractUser):
    first_name = models.CharField(_('First name'), max_length=100)
    last_name = models.CharField('Last name', max_length=100)
    username = models.CharField('Username', max_length=100, null=True, blank=True)
    email = models.EmailField('Email', max_length=100, unique=True)
    bio = models.TextField('About', null=True, blank=True)
    profile_image = models.ImageField('Profile image',
                                      default='profile-images/user-default.png',
                                      upload_to='profile-images/',
                                      null=True, blank=True)
    location = models.CharField('Location', max_length=100, null=True, blank=True)
    occupation = models.CharField('Occupation', max_length=200, null=True, blank=True)
    social_telegram = models.URLField('Telegram', max_length=200, null=True, blank=True)
    social_instagram = models.URLField('Instagram', max_length=200, null=True, blank=True)
    social_facebook = models.URLField('Facebook', max_length=200, null=True, blank=True)
    social_twitter = models.URLField('Twitter', max_length=200, null=True, blank=True)
    social_whatsapp = models.URLField('Whatsapp', max_length=200, null=True, blank=True)
    social_linkedin = models.URLField('LinkedIn', max_length=200, null=True, blank=True)
    social_youtube = models.URLField('YouTube', max_length=200, null=True, blank=True)
    social_github = models.URLField('GitHub', max_length=200, null=True, blank=True)
    social_website = models.URLField('Website', max_length=200, null=True, blank=True)

    objects = UserManager()
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    @property
    def fullname(self):
        return f"{self.first_name} {self.last_name}"

    def get_fullname(self):
        return f"{self.first_name} {self.last_name}"

    def set_fullname(self, value):
        names = value.split()
        self.first_name, self.last_name = names[0], " ".join(names[1:])

    fullname = property(get_fullname, set_fullname)


class Skill(models.Model):
    owner = models.ForeignKey(to=User, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return f'{self.owner} - {self.name}'

app_users/forms.py
from django.forms import ModelForm
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from .models import Skill


User = get_user_model()


class AddInputClass:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for _, field in self.fields.items():
            field.widget.attrs.update({
                'class': 'input input--text',
            })


class UserRegistrationForm(AddInputClass, UserCreationForm):
    class Meta:
        model = User
        fields = ['email', 'first_name', 'last_name', 'password1', 'password2']



class SkillForm(AddInputClass, ModelForm):
    class Meta:
        model = Skill
        fields = ['name', 'description'] 

    def __init__(self, *args, **kwargs):
        AddInputClass.__init__(self, *args, **kwargs)


class AccountForm(AddInputClass, ModelForm):
    class Meta:
        model = User
        exclude = ['password', 'last_login', 'user_permisssion', 'is_superuser', 'is_staff', 'groups', 'is_active', 'date_joined', 'bio', 'occupation']

app_users/views.py
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView
from django.contrib.auth import get_user_model, logout
from django.urls import reverse_lazy, reverse
from django.shortcuts import redirect
from django.utils.translation import gettext_lazy as _

from .models import Skill
from .forms import UserRegistrationForm, SkillForm, AccountForm

User = get_user_model()


class UserRegistrationView(CreateView):
    model = User
    template_name = 'app_users/registration.html'
    form_class = UserRegistrationForm
    success_url = reverse_lazy('login')


def logout_view(request):
    logout(request)
    return redirect('login')


class AccountView(DetailView):
    model = User
    template_name = 'app_users/account.html'
    pk_url_kwarg = 'user_id'
    context_object_name = 'account'


class CreateSkillView(CreateView):
    template_name = 'form.html'
    model = Skill
    form_class = SkillForm


    def form_valid(self, form):
        skill = form.save(commit=False)
        skill.owner = self.request.user
        skill.save()
        return redirect('account', user_id=self.request.user.id)


    def get_context_data(self, *args, **kwargs):
        context =  super().get_context_data(*args, **kwargs)
        context['btn_text'] = _('Create skill')
        return context


    def get_success_url(self) -> str:
        return reverse('account', user_id=self.request.user.id)


class UpdateSkillView(UpdateView):
    template_name = 'form.html'
    model = Skill
    form_class = SkillForm
    pk_url_kwarg = 'skill_id'



    def get_context_data(self, *args, **kwargs):
        context =  super().get_context_data(*args, **kwargs)
        context['btn_text'] = _('Update skill')
        return context


    def get_success_url(self) -> str:
        return reverse('account', kwargs={'user_id': self.request.user.id})


class DeleteSkillView(DeleteView):
    model = Skill
    template_name = 'delete.html'
    pk_url_kwarg = 'skill_id'


    def get_context_data(self, *args, **kwargs):
        context =  super().get_context_data(*args, **kwargs)
        context['confirmation_text'] = _(f'Are you want to delete "{self.get_object().name}"?')
        return context
    

    def get_success_url(self) -> str:
        return reverse('account', kwargs={'user_id': self.request.user.id})


class UpdateAccount(UpdateView):
    template_name = 'form.html'
    model = User
    form_class = AccountForm
    pk_url_kwarg = 'user_id'


    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['btn_text'] = _('Update account')
        return context


    def get_success_url(self):
        return reverse('account', kwargs={'user_id': self.request.user.id})
    

app_users/templates/app_users/account.html
{% extends 'base.html' %} 
{% load i18n %}

{% block content %}
<main class="settingsPage profile my-md">
	<div class="container">
		<div class="layout">
			<div class="column column--1of3">
				<div class="card text-center">
					<div class="card__body dev">
						<a class="tag tag--pill tag--main settings__btn" href="{% url 'update_account' user_id=request.user.id %}">
                            <i class="im im-edit"></i>
                                {% trans 'Edit' %}
                            </a>
						<img
							class="avatar avatar--xl dev__avatar"
							src="{{ account.profile_image.url }}"
						/>
						<h2 class="dev__name">{{ account.fullname }}</h2>
						<p class="dev__title">
                            {% if account.occupation %}
							    {{ account.occupation }}
                            {% else %}
                                {% trans 'No occupation' %}
                            {% endif %}
						</p>
						<p class="dev__location">
                            {% if account.location %}
                                {% trans 'Based in' %} {{ account.location }}
                            {% else %}
                                {% trans 'No location' %}
                            {% endif %}
                        </p>
						<ul class="dev__social">
							{% if account.social_telegram %}
							<li>
								<a title="Telegram" href="{{ account.social_telegram }}" target="_blank">
									<i class="bi bi-telegram"></i>
								</a>
							</li>
							{% endif %}
							
							{% if account.social_instagram %}
							<li>
								<a title="Instagram" href="{{ account.social_instagram }}" target="_blank">
									<i class="bi bi-instagram"></i>
								</a>
							</li>
							{% endif %}
							
							{% if account.social_facebook %}
							<li>
								<a title="Facebook" href="{{ account.social_facebook }}" target="_blank">
									<i class="bi bi-facebook"></i>
								</a>
							</li>
							{% endif %}
							
							{% if account.social_twitter %}
							<li>
								<a title="Twitter" href="{{ account.social_twitter }}" target="_blank">
									<i class="bi bi-twitter"></i>
								</a>
							</li>
							{% endif %}
							
							{% if account.social_whatsapp %}
							<li>
								<a title="WhatsApp" href="{{ account.social_whatsapp }}" target="_blank">
									<i class="bi bi-whatsapp"></i>
								</a>
							</li>
							{% endif %}
							
							{% if account.social_linkedin %}
							<li>
								<a title="LinkedIn" href="{{ account.social_linkedin }}" target="_blank">
									<i class="bi bi-linkedin"></i>
								</a>
							</li>
							{% endif %}
							
							{% if account.social_youtube %}
							<li>
								<a title="YouTube" href="{{ account.social_youtube }}" target="_blank">
									<i class="bi bi-youtube"></i>
								</a>
							</li>
							{% endif %}
							
							{% if account.social_github %}
							<li>
								<a title="GitHub" href="{{ account.social_github }}" target="_blank">
									<i class="bi bi-github"></i>
								</a>
							</li>
							{% endif %}
							
							{% if account.social_website %}
							<li>
								<a title="Personal Website" href="{{ account.social_website }}" target="_blank">
									<i class="bi bi-globe"></i>
								</a>
							</li>
							{% endif %}							
						</ul>
					</div>
				</div>
			</div>
			<div class="column column--2of3">
				<div class="devInfo">
					<h3 class="devInfo__title">{% trans 'About Me' %}</h3>
					<p class="devInfo__about">
                        {% if account.bio %}
                            {{ account.bio|linebreaksbr }}
                        {% else %}
                            {% trans 'No bio' %}
                        {% endif %}
					</p>
				</div>
				<div class="settings">
					<h3 class="settings__title">{% trans 'Skills' %}</h3>
					<a class="tag tag--pill tag--sub settings__btn tag--lg" href="{% url 'create_skill' %}">
						<i class="im im-plus"></i>
						{% trans 'Add Skill' %}
					</a>
				</div>

				<table class="settings__table">
					{% for skill in account.skill_set.all %}
						<tr>
							<td class="settings__tableInfo">
								<h4>{{ skill.name }}</h4>
								<p>
									{{ skill.description|linebreaksbr }}
								</p>
							</td>
							<td class="settings__tableActions">
								<a class="tag tag--pill tag--main settings__btn" href="{% url 'update_skill' skill_id=skill.id %}">
									<i class="im im-edit"></i>
									{% trans 'Edit' %}
								</a>
								<a class="tag tag--pill tag--main settings__btn" href="{% url 'delete_skill' skill_id=skill.id %}">
									<i class="im im-x-mark-circle-o"></i>
									{% trans 'Delete' %}
								</a>
							</td>
						</tr>
					{% endfor %}
				</table>

				<div class="settings">
					<h3 class="settings__title">{% trans 'Projects' %}</h3>
					<a class="tag tag--pill tag--sub settings__btn tag--lg" href="{% url 'project_create' %}">
						<i class="im im-plus"></i>
						{% trans 'Add Project' %}
					</a>
				</div>

				<table class="settings__table">
					{% for project in account.project_set.all %}
						<tr>
							<td class="settings__thumbnail">
								<a href="{% url 'project_detail' project_id=project.id %}"
									><img src="{{ project.image.url }}" alt="{{ project.name }}"
								/></a>
							</td>
							<td class="settings__tableInfo">
								<a href="{% url 'project_detail' project_id=project.id %}">{{ project.name }}</a>
								<p>
									{{ project.description|truncatechars:200|linebreaksbr }}
								</p>
							</td>
							<td class="settings__tableActions">
								<a class="tag tag--pill tag--main settings__btn" href="#"
									><i class="im im-edit"></i> Edit</a
								>
								<a class="tag tag--pill tag--main settings__btn" href="#"
									><i class="im im-x-mark-circle-o"></i> Delete</a
								>
							</td>
						</tr>
					{% endfor %}
				</table>
			</div>
		</div>
	</div>
</main>
{% endblock content %}

app_users/templates/app_users/login.html
{% extends 'base.html' %} 
{% load static %} 

{% block content %}
<div class="auth" style="margin-top: 200px; margin-bottom: 200px;">
	<div class="card">
		<div class="auth__header text-center">
			<a href="{% url 'developers' %}">
				<img src="{% static 'images/icon.svg' %}" alt="icon" />
			</a>
			<h3>Account Login</h3>
			<p>Hello Developer, Welcome Back!</p>
		</div>

		<form action="" class="form auth__form" method="post">
            {% csrf_token %}

			<div style="display: flex; flex-direction: row; gap: 10px; justify-content: center; align-items: center; width: 100%;">
				<div style="width: 90px; border-radius: 50%; border: none; background-color: transparent; justify-content: center;">
					<a href="{% url 'social:begin' 'google-oauth2' %}" style="display: flex; align-items: center; justify-content: center;">
						<div>
							<img src="https://mir-s3-cdn-cf.behance.net/project_modules/1400/2058fb75442843.5c4cd14030bd5.png" alt="Continue with Google">
							Continue with Google
						</div>
					</a>
				</div>
				<div style="width: 50px; border-radius: 50%; border: none; background-color: transparent; justify-content: center;">
					<a href="{% url 'social:begin' 'github' %}" style="display: flex; align-items: center; justify-content: center;">
						<div style="display: flex; gap: 5px; flex-direction: column;">
							<img src="https://github.githubassets.com/assets/GitHub-Mark-ea2971cee799.png" alt="Conitnue with GitHub">
							Continue with GitHub
						</div>
					</a>
				</div>
			</div>

			<br>
			<hr>
			<br>
            
			<div class="form__field">
				<label for="formInput#email">Email: </label>
				<input
					class="input input--text"
					id="formInput#email"
					type="email"
					name="username"
				/>
			</div>

			<div class="form__field">
				<label for="formInput#password">Password: </label>
				<input
					class="input input--password"
					id="formInput#passowrd"
					type="password"
					name="password"
				/>
			</div>

			<div class="auth__actions">
				<input class="btn btn--sub btn--lg" type="submit" value="Log In" />
				<a href="{% url 'password_reset' %}">Forget Password?</a>
			</div>
		</form>
		<div class="auth__alternative">
			<p>Don’t have an Account?</p>
			<a href="{% url 'registration' %}">Sign Up</a>
		</div>
	</div>
</div>
{% endblock content %}

app_users/templates/app_users/password-reset-complete.html
{% extends 'base.html' %} 
{% load i18n %}

{% block content %}
<main class="formPage my-xl">
	<div class="content-box">
		<div class="formWrapper">

			<form class="form" method="POST" action="" enctype="multipart/form-data">
				{% csrf_token %}

                {% blocktrans %}
                    <h1>Password reset complete</h1>
                    <p>Your password has been set. You may go ahead and log in now.</p>
                {% endblocktrans %}

				<a href="{% url 'login' %}" class="btn btn--sub btn--lg my-md" type="submit">{% trans 'Login' %}</a>
			</form>
		</div>
	</div>
</main>
{% endblock content %}

app_users/templates/app_users/password-reset-confirm.html
{% extends 'base.html' %} 
{% load i18n %}

{% block content %}
<main class="formPage my-xl">
	<div class="content-box">
		<div class="formWrapper">
			<form class="form" method="POST" action="" enctype="multipart/form-data">
				{% csrf_token %}
                {% if form %}
                    <h1>{% trans 'Enter new password' %}</h1>
                    <p>{% trans 'Please enter your new password twice so we can verify you typed it in correctly.' %}</p>
                    <br>
                    <div class="form__field">
                        <label for="new_password1">{% trans 'New password' %}: </label>
                        <input class="input input--text" type="password" name="new_password1" maxlength="254" id="new_password1">
                    </div>
                    <div class="form__field">
                        <label for="new_password2">{% trans 'Password confirmation' %}: </label>
                        <input class="input input--text" type="password" name="new_password2" maxlength="254" id="new_password2">
                    </div>

                    <button class="btn btn--sub btn--lg my-md" type="submit">{% trans 'Change my password' %}</button>
                {% else %}
                    <h1>{% trans 'Password reset unsuccessful' %}</h1>
                    <p>{% trans 'The password reset link was invalid, possibly because it has already been used. Please request a new password reset.' %}</p>
                {% endif %}
			</form>
		</div>
	</div>
</main>
{% endblock content %}

app_users/templates/app_users/password-reset-done.html
{% extends 'base.html' %} 
{% load i18n %}

{% block content %}
<main class="formPage my-xl">
	<div class="content-box">
		<div class="formWrapper">

			<form class="form" method="POST" action="" enctype="multipart/form-data">
				{% csrf_token %}

                {% blocktrans %}
                    <h1>Password reset sent</h1>
                    <p>We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.</p>
                    <p>If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.</p>
                {% endblocktrans %}

				<a href="{% url 'login' %}" class="btn btn--sub btn--lg my-md" type="submit">{% trans 'Back to login' %}</a>
			</form>
		</div>
	</div>
</main>
{% endblock content %}

app_users/templates/app_users/password-reset.html
{% extends 'base.html' %} 
{% load i18n %}

{% block content %}
<main class="formPage my-xl">
	<div class="content-box">
		<div class="formWrapper">
			<a class="backButton" href="{% url 'login' %}">
				<i class="bi bi-arrow-left"></i>
			</a>
			<br />

			<form class="form" method="POST" action="" enctype="multipart/form-data">
				{% csrf_token %}

                <div class="form__field">
                    <label for="email">{% trans 'Email' %}: </label>
                    <input class="input input--text" type="email" name="email" maxlength="254" id="email">
                </div>

				<button class="btn btn--sub btn--lg my-md" type="submit">{% trans 'Send email' %}</button>
			</form>
		</div>
	</div>
</main>
{% endblock content %}

app_users/templates/app_users/registration.html
{% extends 'base.html' %} 
{% load static %}

{% block content %}
<div class="auth" style="margin-top: 200px; margin-bottom: 200px;">
	<div class="card">
		<div class="auth__header text-center">
			<a href="{% url 'developers' %}">
				<img src="{% static 'images/icon.svg' %}" alt="icon" />
			</a>
			<h3>Account SignUp</h3>
			<p>Create a new developer account</p>
		</div>

		<form action="" class="form auth__form" method="post">
            {% csrf_token %}

            {% for field in form %}
			<div class="form__field">
				<label for="id_{{ field.name }}">{{ field.label }}: </label>
				{{ field }}
			</div>
            {% endfor %}
			
			<div class="auth__actions">
				<input class="btn btn--sub btn--lg" type="submit" value="Sign up" />
			</div>
		</form>
		<div class="auth__alternative">
			<p>Already have an Account?</p>
			<a href="{% url 'login' %}">Log In</a>
		</div>
	</div>
</div>
{% endblock content %}